# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f36510c73498eb8e077480567753d5d7ae5e5396803fbb3ae7879af0a5090c9951ba2148eb5ff9856942011305b310cb8fe7d95ed9773064e05052ac6c271a24

test:
  secret_key_base: 3dd3dd228e41b5aa556f030ea669146c4082a40b49ecc7f561465f70d7a316b65e03ed76a65dcf27dbe4ac84f96d5e057a29054c24cffb67688f75cb93d9a32b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
